# Generated by Django 6.1.1 on 2026-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.PositiveIntegerField(help_text='Duration in months')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
