# Generated by Django 6.1.1 on 2026-09-08 17:53

import django.core.validators
from django.db import migrations, models
from django.utils.text import slugify


def unique_slugs(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    seen = set()
    for project in Project.objects.order_by("pk"):
        base = (project.slug or slugify(project.title) or "project")[:200]
        if base.isdecimal():
            base = f"project-{base}"
        candidate = base
        suffix = 2
        while candidate in seen:
            candidate = f"{base}-{suffix}"
            suffix += 1
        seen.add(candidate)
        if project.slug != candidate:
            Project.objects.filter(pk=project.pk).update(slug=candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='sustainability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
