import { useCallback, useEffect, useState } from 'react';
import { MessageCircle, ThumbsUp, Reply, Pencil, Trash2, Flag, Send, LoaderCircle } from 'lucide-react';
import api, { errorMessage } from '../Services/api';
import { useAuth } from '../context/AuthContext';
import { useProduct } from '../context/ProductContext';
import { useToast } from '../context/ToastContext';
import Dialog, { ConfirmDialog } from './Dialog';
import { ErrorState } from './ui';

function relativeTime(value) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 1 ? 'Just now' : minutes < 60 ? `${minutes} min ago` : minutes < 1440 ? `${Math.floor(minutes / 60)} hr ago` : new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); }
function CommentForm({ onSubmit, initial = '', onCancel = null, label = 'Post comment' }) {
  const [body, setBody] = useState(initial);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const submit = async event => { event.preventDefault(); if (!body.trim() || busy) return; setBusy(true); setError(''); try { await onSubmit(body.trim()); setBody(''); } catch (reason) { setError(reason.response?.data?.body?.[0] || errorMessage(reason)); } finally { setBusy(false); } };
  return <form className="comment-form" onSubmit={submit}><label className="sr-only" htmlFor={`comment-body-${label}`}>{label === 'Post comment' ? 'Your comment' : label}</label><textarea id={`comment-body-${label}`} value={body} maxLength={2000} rows={3} required disabled={busy} onChange={event => setBody(event.target.value)} placeholder="A question, a perspective, a possibility…"/><div className="comment-form-footer"><span>{body.length.toLocaleString()} / 2,000</span><div>{onCancel && <button type="button" className="btn btn-secondary btn-small" disabled={busy} onClick={onCancel}>Cancel</button>}<button type="submit" className="btn btn-primary btn-small" disabled={busy || !body.trim()}>{busy ? <LoaderCircle size={15} className="spin"/> : <Send size={15}/>} {busy ? 'Posting…' : label}</button></div></div>{error && <p className="field-error" role="alert">{error}</p>}</form>;
}
export default function Comments({ project }) {
  const { user, isAuthenticated } = useAuth();
  const { requireLogin } = useProduct();
  const { toast } = useToast();
  const [comments, setComments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [editing, setEditing] = useState(null);
  const [replying, setReplying] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [reporting, setReporting] = useState(null);
  const [reason, setReason] = useState('');
  const [busy, setBusy] = useState(false);
  const [dialogError, setDialogError] = useState('');
  const [reacting, setReacting] = useState({});
  const load = useCallback(() => api.get(`/projects/${project.id}/comments/`).then(({ data }) => { setComments(data); setError(''); }).catch(reason => setError(errorMessage(reason))).finally(() => setLoading(false)), [project.id]);
  useEffect(() => { load(); }, [load, user?.id]);
  const changed = () => window.dispatchEvent(new Event('vestra:data-changed'));
  const post = async (body, parent = null) => { const { data } = await api.post(`/projects/${project.id}/comments/`, { body, parent }); setComments(current => [...current, data]); setReplying(null); toast({ title: parent ? 'Reply posted' : 'Comment posted' }); changed(); };
  const edit = async (comment, body) => { const { data } = await api.patch(`/community/comments/${comment.id}/`, { body }); setComments(current => current.map(item => item.id === data.id ? data : item)); setEditing(null); toast({ title: 'Comment updated' }); };
  const react = async comment => { if (!isAuthenticated) { requireLogin('comment', project); return; } if (reacting[comment.id]) return; setReacting(current => ({ ...current, [comment.id]: true })); try { await api[comment.reacted ? 'delete' : 'post'](`/community/comments/${comment.id}/react/`); await load(); changed(); } catch (reason) { toast({ title: 'Could not update reaction', message: errorMessage(reason) }); } finally { setReacting(current => ({ ...current, [comment.id]: false })); } };
  const remove = async () => { setBusy(true); setDialogError(''); try { await api.delete(`/community/comments/${deleting.id}/`); await load(); setDeleting(null); toast({ title: 'Comment deleted' }); changed(); } catch (reason) { setDialogError(errorMessage(reason)); } finally { setBusy(false); } };
  const report = async event => { event.preventDefault(); if (!reason.trim()) return; setBusy(true); setDialogError(''); try { await api.post(`/community/comments/${reporting.id}/report/`, { reason }); setReporting(null); setReason(''); toast({ title: 'Report submitted', message: 'An administrator will review this comment.' }); } catch (reason) { setDialogError(errorMessage(reason)); } finally { setBusy(false); } };
  const renderComment = (comment, depth = 0) => {
    const replies = comments.filter(item => item.parent === comment.id);
    const hidden = comment.is_hidden || comment.is_deleted;
    const mine = user?.id === comment.author?.id;
    const name = comment.author?.first_name || comment.author?.username || 'Member';
    return <article className={`discussion-comment ${depth ? 'is-reply' : ''}`} key={comment.id} id={`comment-${comment.id}`}><div className="comment-heading"><span className={`avatar avatar-${comment.author?.avatar || 'sage'}`}>{name.slice(0, 1).toUpperCase()}</span><div><strong>{name}</strong><span><time dateTime={comment.created_at} title={new Date(comment.created_at).toLocaleString()}>{relativeTime(comment.created_at)}</time>{comment.is_edited && ' · Edited'}</span></div>{mine && !hidden && <span className="comment-yours">You</span>}</div>{editing === comment.id ? <CommentForm initial={comment.body} label="Save changes" onCancel={() => setEditing(null)} onSubmit={body => edit(comment, body)}/> : <p className={`comment-body ${hidden ? 'muted' : ''}`}>{hidden ? comment.is_deleted ? 'This comment was deleted.' : 'This comment is hidden while it is reviewed.' : comment.body}</p>}{!hidden && editing !== comment.id && <div className="comment-actions"><button aria-label={`Mark comment by ${name} useful`} aria-pressed={comment.reacted} disabled={reacting[comment.id]} onClick={() => react(comment)}><ThumbsUp size={14}/><span>Useful{comment.reaction_count > 0 ? ` · ${comment.reaction_count}` : ''}</span></button>{depth < 2 && <button onClick={() => { if (!isAuthenticated) requireLogin('comment', project); else { setReplying(replying === comment.id ? null : comment.id); setEditing(null); } }}><Reply size={14}/> Reply</button>}{mine ? <><button onClick={() => { setEditing(comment.id); setReplying(null); }}><Pencil size={13}/> Edit</button><button onClick={() => { setDeleting(comment); setDialogError(''); }}><Trash2 size={13}/> Delete</button></> : <button onClick={() => { if (!isAuthenticated) requireLogin('comment', project); else { setReporting(comment); setDialogError(''); } }} aria-label={`Report comment by ${name}`}><Flag size={13}/><span className="sr-only">Report</span></button>}</div>}{replying === comment.id && <CommentForm label="Post reply" onCancel={() => setReplying(null)} onSubmit={body => post(body, comment.id)}/>}<div className="comment-replies">{depth < 3 && replies.map(reply => renderComment(reply, depth + 1))}</div></article>;
  };
  return <section className="project-discussion" id="discussion"><div className="discussion-title"><div><p className="eyebrow">BETTER IDEAS BEGIN WITH A CONVERSATION</p><h2>Discussion <span>· {comments.filter(c => !c.is_deleted && !c.is_hidden).length} comments</span></h2></div><MessageCircle size={27} strokeWidth={1.3}/></div><p className="discussion-intro">Ask thoughtful questions. Share what you notice. Learn from another perspective.</p>{isAuthenticated ? <CommentForm onSubmit={post}/> : <div className="discussion-invite"><span className="avatar">?</span><div><strong>Your perspective belongs here.</strong><p>Sign in to add your voice to the conversation.</p></div><button className="btn btn-primary btn-small" onClick={() => requireLogin('comment', project)}>Join the discussion</button></div>}{loading ? <div className="comment-skeletons" aria-label="Loading comments" role="status">{[0,1].map(item => <div key={item}><div className="skeleton skeleton-title"/><div className="skeleton skeleton-line"/><div className="skeleton skeleton-line"/></div>)}</div> : error ? <ErrorState message={error} onRetry={load}/> : comments.length ? <div className="comments-list">{comments.filter(comment => !comment.parent).map(comment => renderComment(comment))}</div> : <div className="discussion-empty"><MessageCircle size={28}/><h3>The conversation starts with you.</h3><p>No comments yet. What stands out about this project?</p></div>}<ConfirmDialog open={Boolean(deleting)} onClose={() => setDeleting(null)} onConfirm={remove} busy={busy} title="Delete your comment?" description={dialogError || 'Your text will be removed. Replies will remain so the conversation still makes sense.'} confirmLabel="Delete comment"/><Dialog open={Boolean(reporting)} onClose={() => !busy && setReporting(null)} title="Help keep this space thoughtful." description="Tell us why this comment needs a review. Reports are visible only to administrators."><form onSubmit={report} className="simple-form"><label htmlFor="report-reason">Reason for reporting</label><textarea id="report-reason" value={reason} onChange={event => setReason(event.target.value)} maxLength={500} minLength={5} required rows={4}/><small>{reason.length} / 500</small>{dialogError && <p className="field-error" role="alert">{dialogError}</p>}<div className="dialog-actions"><button type="button" className="btn btn-secondary" disabled={busy} onClick={() => setReporting(null)}>Cancel</button><button className="btn btn-primary" disabled={busy || reason.trim().length < 5}>{busy ? 'Submitting…' : 'Submit report'}</button></div></form></Dialog></section>;
}
