/* Real production-browser journeys. Uses isolated accounts and removes only its own test data. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '../..');
const base = process.env.E2E_BASE_URL || 'http://127.0.0.1:4173';
const username = `qa_public_${Date.now().toString(36)}`;
const actor = `${username}_actor`;
const password = 'Vestra-Explore-Purpose-82!';
const email = `${username}@example.test`;
const artifacts = path.join(root, 'artifacts/public-e2e', new Date().toISOString().replace(/[:.]/g, '-'));
fs.mkdirSync(artifacts, { recursive: true });
const results = [], errors = [], warnings = [];
let browser, page, context, token, actorToken, expectedErrors = false;
const wait = async (predicate, message, timeout = 12000) => { const start = Date.now(); while (Date.now() - start < timeout) { if (await predicate()) return; await new Promise(resolve => setTimeout(resolve, 70)); } throw new Error(message); };
async function request(route, method = 'GET', data, auth = token) { const response = await fetch(`${base}/api${route}`, { method, signal: AbortSignal.timeout(15000), headers: { 'Content-Type':'application/json', ...(auth ? { Authorization:`Bearer ${auth}` } : {}) }, ...(data !== undefined ? { body:JSON.stringify(data) } : {}) }); if (!response.ok) throw new Error(`${method} ${route}: ${response.status} ${await response.text()}`); return response.status === 204 ? null : response.json(); }
async function check(name, run) { try { await run(); results.push({ name, status:'PASS' }); process.stdout.write(`PASS ${name}\n`); } catch (error) { results.push({ name, status:'FAIL', message:error.message }); await page?.screenshot({ path:path.join(artifacts, 'failure.png'), fullPage:true }).catch(() => {}); throw error; } }
async function navigate(route) { await page.goto(`${base}${route}`, { waitUntil:'networkidle' }); await wait(async () => !await page.locator('.skeleton-grid,.account-skeleton,.admin-skeleton').count(), `Page still loading: ${route}`); }
async function capture(name) { await page.evaluate(async () => { for (let top = 0; top < document.documentElement.scrollHeight; top += 650) { window.scrollTo({ top, behavior:'instant' }); await new Promise(resolve => setTimeout(resolve, 25)); } window.scrollTo({ top:0, behavior:'instant' }); }); await page.waitForTimeout(650); await page.screenshot({ path:path.join(artifacts, `${name}.png`), fullPage:true }); await page.screenshot({ path:path.join(artifacts, `${name}-viewport.png`) }); }
async function login(targetPage = page) { await targetPage.getByLabel('Email or username').fill(email); await targetPage.getByLabel('Password', { exact:true }).fill(password); await targetPage.getByRole('button', { name:'Sign in', exact:true }).click(); await targetPage.waitForURL(url => !url.pathname.includes('login')); }
async function logout() { await page.getByLabel('Account menu').click(); await page.getByRole('navigation', { name:'Your account' }).getByRole('button', { name:'Log out' }).click(); await wait(async () => !await page.getByLabel('Account menu').count(), 'Account did not sign out'); }
async function openSimulation() { await page.getByRole('button', { name:'Simulate investment', exact:true }).filter({ visible:true }).first().click(); await page.getByRole('dialog', { name:'Simulate an allocation' }).waitFor(); }

(async () => {
  try {
    browser = await chromium.launch({ executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless:true });
    context = await browser.newContext({ viewport:{ width:1440, height:1000 }, permissions:['clipboard-read','clipboard-write'] });
    page = await context.newPage(); page.setDefaultTimeout(12000);
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'warning') warnings.push(message.text()); if (message.type() === 'error' && !expectedErrors && !message.text().includes('status of 404')) errors.push(message.text()); });
    const catalog = await request('/projects/', 'GET', undefined, null);
    const nova = catalog.find(project => project.slug === 'nova-energy');
    const aqua = catalog.find(project => project.slug === 'aqualoop');
    assert(nova && aqua, 'The existing seeded catalog is required');
    await check('Homepage, real catalog, local fonts and project-card slug routes', async () => { await navigate('/'); assert(await page.locator('h1').isVisible()); await page.evaluate(() => document.fonts.ready); assert(await page.evaluate(() => document.fonts.check('400 14px Manrope'))); await page.locator('.project-card h3 a').first().click(); await page.waitForURL(/\/projects\/[a-z]/); assert(await page.locator('.project-detail-page h1').isVisible()); });
    await check('Visitor save → accessible sign-in dialog → registration → saved action restored', async () => { await navigate(`/projects/${nova.slug}`); await page.getByRole('button', { name:`Save ${nova.title}`, exact:true }).click(); const dialog = page.getByRole('dialog', { name:'Make this possibility yours.' }); await dialog.waitFor(); await dialog.getByRole('link', { name:'Create an account' }).click(); await page.getByLabel('Username', { exact:true }).fill(username); await page.getByLabel('Email address', { exact:true }).fill(email); await page.getByLabel('Password', { exact:true }).fill(password); await page.getByLabel('Confirm password', { exact:true }).fill(password); await page.getByRole('button', { name:/Create.*account/ }).click(); await page.waitForURL(`**/projects/${nova.slug}`); await wait(async () => await page.getByRole('button', { name:`Unsave ${nova.title}`, exact:true }).count(), 'Pending save not restored'); token = (await request('/users/login/', 'POST', { username, password }, null)).access; assert((await request('/community/saved/')).some(project => project.id === nova.id)); });
    await check('Visitor discussion → login → return to exact project discussion', async () => { await logout(); await page.getByRole('button', { name:'Join the discussion', exact:true }).click(); const dialog = page.getByRole('dialog', { name:'Join the discussion.' }); await dialog.getByRole('link', { name:'Log in', exact:true }).click(); await login(); assert.equal(new URL(page.url()).hash, '#discussion'); await page.getByLabel('Your comment', { exact:true }).waitFor(); });
    let rootComment;
    const original = `A thoughtful QA perspective ${username}. How does this project support long-term learning?`;
    const edited = `An edited QA perspective ${username}. ${'LearningTogether'.repeat(45)}`;
    await check('Comments create, persist after reload, edit and show edited state', async () => { await page.getByLabel('Your comment', { exact:true }).fill(original); await page.getByRole('button', { name:'Post comment', exact:true }).click(); await page.getByText(original, { exact:true }).waitFor(); rootComment = (await request(`/projects/${nova.id}/comments/`)).find(comment => comment.body === original); assert(rootComment); await navigate(`/projects/${nova.slug}#discussion`); const article = page.locator(`#comment-${rootComment.id}`); await article.getByRole('button', { name:'Edit', exact:true }).click(); await article.getByLabel('Save changes', { exact:true }).fill(edited); await article.getByRole('button', { name:'Save changes', exact:true }).click(); await article.getByText(edited, { exact:true }).waitFor(); assert((await article.innerText()).includes('Edited')); });
    await check('Nested replies, sensible depth, useful reactions and database persistence', async () => { const article = page.locator(`#comment-${rootComment.id}`); await article.getByRole('button', { name:'Reply', exact:true }).click(); await article.getByLabel('Post reply', { exact:true }).fill(`First reply ${username}`); await article.getByRole('button', { name:'Post reply', exact:true }).click(); let comments = await request(`/projects/${nova.id}/comments/`); const first = comments.find(comment => comment.body === `First reply ${username}`); const reply = page.locator(`#comment-${first.id}`); await reply.getByRole('button', { name:'Reply', exact:true }).click(); await reply.getByLabel('Post reply', { exact:true }).fill(`Second reply ${username}`); await reply.getByRole('button', { name:'Post reply', exact:true }).click(); comments = await request(`/projects/${nova.id}/comments/`); const second = comments.find(comment => comment.body === `Second reply ${username}`); assert(second); assert.equal(await page.locator(`#comment-${second.id}`).getByRole('button', { name:'Reply', exact:true }).count(), 0); await page.locator(`#comment-${second.id}`).getByRole('button', { name:/Mark comment.*useful/ }).click(); await wait(async () => (await request(`/projects/${nova.id}/comments/`)).find(comment => comment.id === second.id)?.reaction_count === 1, 'Useful reaction did not persist'); });
    await check('Comment report dialog submits to actual moderation queue', async () => { await request('/users/register/', 'POST', { username:actor, email:`${actor}@example.test`, password }, null); actorToken = (await request('/users/login/', 'POST', { username:actor,password }, null)).access; const other = await request(`/projects/${nova.id}/comments/`, 'POST', { body:`Another perspective ${username}` }, actorToken); await navigate(`/projects/${nova.slug}#discussion`); await page.locator(`#comment-${other.id}`).getByRole('button', { name:/Report comment/ }).click(); const dialog = page.getByRole('dialog', { name:'Help keep this space thoughtful.' }); await dialog.getByLabel('Reason for reporting').fill(`QA review request ${username}`); await dialog.getByRole('button', { name:'Submit report' }).click(); await dialog.waitFor({ state:'hidden' }); await page.getByText('Report submitted', { exact:true }).waitFor(); });
    await check('Delete comment confirmation preserves reply threads', async () => { const article = page.locator(`#comment-${rootComment.id}`); await article.getByRole('button', { name:'Delete', exact:true }).first().click(); const dialog = page.getByRole('dialog', { name:'Delete your comment?' }); await dialog.getByRole('button', { name:'Cancel', exact:true }).click(); assert(await article.getByText(edited, { exact:true }).isVisible()); await article.getByRole('button', { name:'Delete', exact:true }).first().click(); await page.getByRole('dialog', { name:'Delete your comment?' }).getByRole('button', { name:'Delete comment', exact:true }).click(); await article.getByText('This comment was deleted.', { exact:true }).waitFor(); assert(await article.getByText(`First reply ${username}`, { exact:true }).isVisible()); assert((await request(`/projects/${nova.id}/comments/`)).find(comment => comment.id === rootComment.id).is_deleted); });
    await check('Project share dialog copy link, Escape and focus restoration', async () => { await page.getByRole('button', { name:'Share', exact:true }).click(); const dialog = page.getByRole('dialog', { name:'Ideas travel further together.' }); await dialog.getByRole('button', { name:'Copy', exact:true }).click(); await dialog.getByRole('button', { name:'Copied', exact:true }).waitFor(); assert.equal(await page.evaluate(() => navigator.clipboard.readText()), `${base}/projects/${nova.slug}`); assert((await dialog.getByRole('link', { name:'Email',exact:true }).getAttribute('href')).startsWith('mailto:')); await page.keyboard.press('Escape'); await dialog.waitFor({ state:'hidden' }); assert.equal(await page.evaluate(() => document.activeElement.textContent.trim()), 'Share'); });
    await check('Global search slash and Ctrl K shortcuts, organization/tag search, keyboard result navigation', async () => { await page.locator('main').focus(); await page.keyboard.press('/'); const dialog = page.getByRole('dialog', { name:'Follow your curiosity.' }); const input = dialog.getByRole('combobox'); await input.fill('Nova Energy'); await wait(async () => (await dialog.locator('[role=option] strong').allTextContents())[0] === 'Nova Energy', 'Search results did not arrive'); await input.press('Enter'); await dialog.waitFor({ state:'hidden' }); assert.equal(new URL(page.url()).pathname, `/projects/${nova.slug}`); await page.keyboard.press('Control+k'); await page.getByRole('combobox').fill(nova.organization); await wait(async () => (await page.locator('[role=option] strong').allTextContents()).includes(nova.title), 'Organization not searchable'); await page.keyboard.press('Escape'); });
    await check('Comparison adds two projects and persists to account across fresh browser sessions', async () => { await page.getByRole('button', { name:`Compare ${nova.title}`, exact:true }).click(); await navigate(`/projects/${aqua.slug}`); await page.getByRole('button', { name:`Compare ${aqua.title}`, exact:true }).click(); await wait(async () => (await request('/community/comparison/')).length === 2, 'Comparison not persisted'); await navigate('/compare'); assert.equal(await page.locator('.comparison-table thead a').count(), 2); const secondContext = await browser.newContext(); const secondPage = await secondContext.newPage(); await secondPage.goto(`${base}/login`); await login(secondPage); await secondPage.goto(`${base}/compare`); await secondPage.locator('.comparison-table').waitFor(); assert.equal(await secondPage.locator('.comparison-table thead a').count(), 2); await secondContext.close(); });
    await check('Modal simulator validates and saves exact $1,000 / $150 / $1,150 scenario', async () => { await navigate(`/projects/${nova.slug}`); await openSimulation(); const dialog = page.getByRole('dialog', { name:'Simulate an allocation' }); const input = dialog.getByLabel('Simulated investment amount'); await input.fill('-1'); await input.blur(); assert(await dialog.locator('.field-error').count()); await input.fill('1000'); await wait(async () => (await dialog.locator('.simulation-profit strong').innerText()) === '+$150', 'Profit incorrect'); assert.equal(await dialog.locator('.simulation-total strong').innerText(), '$1,150'); await dialog.getByRole('button', { name:'Add to simulated portfolio', exact:true }).click(); await dialog.getByText('Simulation saved', { exact:true }).waitFor(); const saved = (await request('/investments/')).find(item => item.project.id === nova.id); assert.equal(saved.amount,'1000.00'); assert.equal(saved.expected_profit,'150.00'); assert.equal(saved.estimated_total,'1150.00'); await dialog.getByRole('button', { name:'View your portfolio' }).click(); await page.waitForURL('**/portfolio'); });
    await check('Search, category/location/impact/status/return filters and sorting use real API results', async () => { await navigate('/projects'); await page.getByLabel('Search projects', { exact:true }).fill('solar'); await wait(async () => !await page.locator('.skeleton-grid').count(), 'Search not complete'); await page.waitForTimeout(400); let apiResults = await request('/projects/?search=solar'); assert.deepEqual(await page.locator('.project-card h3').allTextContents(), apiResults.map(project => project.title)); await page.getByRole('button', { name:'Clear filters', exact:true }).click(); await page.locator('#filter-location').selectOption(nova.location); await page.locator('#filter-impact_area').selectOption(nova.impact_area); await page.locator('#filter-status').selectOption('active'); await page.locator('#filter-return-min').fill('14'); await page.locator('#filter-return-max').fill('16'); await page.locator('#project-sort').selectOption('-impact_score'); await page.waitForTimeout(400); await wait(async () => !await page.locator('.skeleton-grid').count(), 'Filters not complete'); apiResults = await request(`/projects/?${new URL(page.url()).searchParams}`); assert.deepEqual(await page.locator('.project-card h3').allTextContents(), apiResults.map(project => project.title)); });
    await check('Contact and feedback forms submit actual inbox messages with success feedback', async () => { for (const route of ['/contact','/feedback']) { await navigate(route); await page.getByLabel('Name', { exact:true }).fill(username); await page.getByLabel('Email', { exact:true }).fill(email); if (route === '/contact') await page.getByLabel('Subject', { exact:true }).fill(`QA contact ${username}`); else await page.getByLabel('Feedback type').selectOption('bug'); await page.getByLabel(route === '/contact' ? 'Message' : 'Your thoughts', { exact:true }).fill(`A useful learning platform feedback message ${username}.`); await page.getByRole('button', { name:route === '/contact' ? 'Send message' : 'Send feedback', exact:true }).click(); await page.locator('.contact-success').waitFor(); assert((await page.locator('.contact-success').innerText()).includes('saved for the team')); } });
    await check('Learn, FAQ accordion, legal links and ordinary-user admin isolation', async () => { await navigate('/how-it-works'); assert.equal(await page.locator('.learning-step').count(),4); await navigate('/faq'); const first = page.locator('.vestra-accordion button').first(); await first.click(); assert.equal(await first.getAttribute('aria-expanded'),'true'); await first.click(); assert.equal(await first.getAttribute('aria-expanded'),'false'); for (const route of ['/privacy','/terms']) { await navigate(route); assert.equal(await page.locator('.legal-page>section').count(),5); } await navigate('/admin'); assert.equal(new URL(page.url()).pathname,'/403'); assert.equal(await page.locator('.site-header a[href="/admin"]').count(),0); });
    await check('Mobile menu, modal filter drawer, focus containment and reduced motion', async () => { await page.setViewportSize({ width:390,height:844 }); await navigate('/projects'); const trigger = page.getByRole('button',{ name:'Open menu', exact:true }); await trigger.click(); const menu = page.getByRole('dialog',{ name:'A world of possibility.' }); await menu.waitFor(); for (let i=0;i<20;i++) { await page.keyboard.press('Tab'); assert(await menu.evaluate(dialog => dialog.contains(document.activeElement)), 'Modal focus escaped'); } await page.keyboard.press('Escape'); assert.equal(await page.evaluate(() => document.activeElement.getAttribute('aria-label')),'Open menu'); await page.getByRole('button',{ name:/^Filters/ }).click(); const filters = page.getByRole('dialog',{ name:'Find what matters to you.' }); await filters.getByLabel('Category',{ exact:true }).selectOption('Water'); await filters.getByRole('button',{ name:/Show.*projects/ }).click(); await wait(async () => !await page.locator('.skeleton-grid').count(), 'Mobile filtering unfinished'); assert((await page.locator('.project-visual-category').allTextContents()).every(value => value === 'Water')); await page.emulateMedia({ reducedMotion:'reduce' }); await navigate(`/projects/${nova.slug}`); await openSimulation(); const modal = page.getByRole('dialog',{ name:'Simulate an allocation' }); assert.equal(await modal.evaluate(el => getComputedStyle(el).animationName),'none'); await page.keyboard.press('Escape'); await page.emulateMedia({ reducedMotion:'no-preference' }); });
    const routes = ['/', '/projects', `/projects/${nova.slug}`, '/compare', '/about', '/how-it-works', '/faq', '/contact', '/feedback', '/privacy', '/terms', '/403', '/missing-page'];
    for (const width of [1920,1728,1440,1280,1024,768,430,390]) {
      await page.setViewportSize({ width, height:width < 768 ? 844 : 1000 });
      for (const route of routes) await check(`Responsive ${route} at ${width}px`, async () => { await navigate(route); assert(await page.locator('main h1').isVisible(), `Missing heading at ${route}`); const size = await page.evaluate(() => ({ viewport:innerWidth, document:document.documentElement.scrollWidth, main:document.querySelector('main').scrollWidth })); assert(size.document <= width + 1 && size.main <= width + 1, `Horizontal overflow ${JSON.stringify(size)}`); assert(!/\bundefined\b|NaN/.test(await page.locator('main').innerText()), 'Undefined value is visible'); if ([1440,768,390].includes(width) && ['/',`/projects/${nova.slug}`,'/compare','/how-it-works','/contact'].includes(route)) await capture(`${route.replaceAll('/','-') || 'home'}-${width}`); });
    }
    await check('Saved and followed removals remain connected after reload', async () => { await navigate('/saved'); await page.getByRole('button',{ name:`Unsave ${nova.title}`,exact:true }).click(); await wait(async () => !(await request('/community/saved/')).some(project => project.id === nova.id), 'Unsave failed'); await navigate(`/projects/${nova.slug}`); await page.getByRole('button',{ name:'Follow project',exact:true }).click(); await wait(async () => (await request('/community/following/')).some(project => project.id === nova.id), 'Follow failed'); await page.getByRole('button',{ name:'Following',exact:true }).click(); await wait(async () => !(await request('/community/following/')).some(project => project.id === nova.id), 'Unfollow failed'); });
    await check('Offline/API-error presentation and recovery', async () => { expectedErrors = true; await page.route('**/api/projects/**', route => route.abort('failed')); await navigate('/projects'); await page.locator('.error-state').waitFor(); assert((await page.locator('.error-state').innerText()).includes('connect')); await page.unroute('**/api/projects/**'); await page.getByRole('button',{ name:'Try again',exact:true }).click(); await page.locator('.project-card').first().waitFor(); expectedErrors = false; });
    await check('No unhandled errors, console warnings, dead local links or broken images', async () => { assert.deepEqual(errors,[]); assert.deepEqual(warnings,[]); assert.equal(await page.locator('a[href="#"]').count(),0); assert.equal(await page.locator('img').evaluateAll(images => images.filter(image => !image.hidden && image.complete && image.naturalWidth === 0).length),0); });
  } catch (error) { process.stderr.write(error.stack + '\n'); process.exitCode = 1; }
  finally {
    await browser?.close();
    const code = `import os; from django.contrib.auth import get_user_model; from community.models import Comment, InboxMessage; names=os.environ['VESTRA_PUBLIC_QA_NAMES'].split(','); assert all(n.startswith('qa_public_') for n in names); Comment.objects.filter(author__username__in=names).delete(); InboxMessage.objects.filter(email__in=[n+'@example.test' for n in names]).delete(); get_user_model().objects.filter(username__in=names,email__in=[n+'@example.test' for n in names]).delete()`;
    const cleaned = spawnSync(path.join(root,'backend/venv/Scripts/python.exe'), ['manage.py','shell','-c',code], { cwd:path.join(root,'backend'), env:{...process.env,VESTRA_PUBLIC_QA_NAMES:`${username},${actor}`}, encoding:'utf8' });
    if (cleaned.status !== 0) { process.stderr.write(cleaned.stderr); process.exitCode = 1; }
    fs.writeFileSync(path.join(artifacts,'report.json'), JSON.stringify({ status:process.exitCode ? 'FAIL':'PASS', base, results, errors, warnings, cleanup:cleaned.status === 0 },null,2));
    process.stdout.write(`Report: ${path.join(artifacts,'report.json')}\n`);
  }
})();
