import { Link, useLocation } from 'react-router-dom';
import { ArrowUpRight, Compass, GitCompareArrows, ChartPie, Sprout } from 'lucide-react';
import { Reveal } from '../Components/ui';
import Accordion from '../Components/Accordion';
import ProjectVisual from '../Components/ProjectVisual';
const questions = [
  ['Is Vestra a real investment platform?', 'Vestra is an educational simulation. It helps you explore allocation, risk and impact through fictional projects. It does not broker, process, or offer real investments.'],
  ['Is real money used?', 'No. Every amount is fictional. You never connect a bank account, make a deposit, or transfer funds through Vestra.'],
  ['What does simulated return mean?', 'It is a simple illustrative scenario for a project’s full stated duration. A $1,000 allocation at 15% gives $150 expected profit and $1,150 estimated total. It is not a forecast, a guarantee, an annual rate, or a compounded return.'],
  ['What is an impact score?', 'An illustrative score from 0 to 100 set for each fictional project by its administrator. It helps compare the educational scenarios, but is not independently verified research. Your portfolio impact score weights each project’s score by your allocation.'],
  ['Can I create multiple simulations?', 'Yes. Add as many fictional allocations as you want. The portfolio combines allocations to the same project in its overview, while preserving each scenario so you can change or remove it. Each saved scenario keeps the return rate it was created with.'],
  ['How are projects selected?', 'Administrators curate and publish projects. The current application operates in demo mode with an explicitly fictional catalog. Drafts remain private until an administrator publishes them.'],
  ['Is my portfolio real?', 'Your saved data belongs to your account and persists between visits. The portfolio itself is entirely simulated. Its value history records your allocation changes; it is not a live market price feed.'],
  ['Why follow or save a project?', 'Saving creates your personal reading list. Following also connects you to notifications when an administrator updates the project. Manage your preferences in Settings.'],
  ['Who can see my activity?', 'Your portfolio, saved projects, follows and account activity are private to your account and authorized administrators. Comments are public and show your chosen display name. Never post private information in a discussion.'],
  ['Can I change my mind?', 'Absolutely. Edit or remove portfolio allocations, unsave an idea, unfollow a project, or edit your own comments. Exploring another perspective is part of the experience.'],
];
export default function Learn() {
  const { pathname } = useLocation();
  if (pathname === '/faq') return <div className="container editorial-page faq-page"><Reveal><p className="eyebrow">A LITTLE CLARITY GOES A LONG WAY</p><h1 className="page-heading">Good questions.<br/><span className="serif-emphasis">Thoughtful answers.</span></h1><p className="page-intro">Everything you need to feel at home in the simulation.</p></Reveal><Accordion items={questions}/><div className="editorial-next"><h2>Still curious?</h2><p>Tell us what is on your mind.</p><Link className="btn btn-primary" to="/contact">Get in touch<ArrowUpRight size={17}/></Link></div></div>;
  const steps = [ { title:'Explore', subtitle:'Start with what matters.', text:'Clean energy. Better health. Access to water. Discover fictional projects connected to the challenges you care about, then save the ideas that stay with you.', icon:Compass, category:'Clean Energy', action:'Find your first idea', url:'/projects'}, {title:'Understand', subtitle:'Put possibility in perspective.', text:'Read the story behind a project. Ask a question in the discussion. Compare impact, risk and scenario returns side by side. Each perspective adds another piece to the picture.',icon:GitCompareArrows,category:'Water', action:'Compare possibilities',url:'/compare'}, {title:'Simulate',subtitle:'Make room for what if.',text:'Choose a fictional amount and see the estimated outcome before adding it to your portfolio. Try $1,000 at 15%: $150 in expected profit and $1,150 in estimated total value. No money moves.',icon:ChartPie,category:'Technology',action:'Build your simulated portfolio',url:'/portfolio'}, {title:'Learn',subtitle:'See the whole picture.',text:'Look at your allocation across categories, review the impact of your choices, and try a different balance. Your history reflects the changes you make, giving each decision a useful context.',icon:Sprout,category:'Sustainable Agriculture',action:'Open your dashboard',url:'/dashboard'} ];
  return <div className="container editorial-page how-page"><Reveal><p className="eyebrow">CURIOSITY IS A GOOD PLACE TO START</p><h1 className="page-heading">A little exploration.<br/><span className="serif-emphasis">A lot of perspective.</span></h1><p className="page-intro">Four steps from an interesting idea to a clearer understanding of your choices.</p></Reveal><div className="learning-steps">{steps.map((step,index) => <Reveal key={step.title} className="learning-step"><div className="learning-step-text"><span className="learning-number">0{index + 1}</span><span className="eyebrow"><step.icon size={17}/>{step.title}</span><h2>{step.subtitle}</h2><p>{step.text}</p><Link className="text-link" to={step.url}>{step.action}<ArrowUpRight size={17}/></Link></div><div className="learning-step-visual"><ProjectVisual category={step.category} title={step.title}/><span>VESTRA / A DIFFERENT WAY TO LEARN</span></div></Reveal>)}</div><section className="disclaimer-panel"><p className="eyebrow">THE FREEDOM TO EXPLORE</p><h2>All the perspective.<br/>None of the financial pressure.</h2><p>Vestra is an educational simulation. Its projects, funding figures and outcomes are fictional. No real money is invested. Scenarios omit real-world factors such as fees, tax, inflation, and losses.</p><Link to="/faq" className="text-link">Understand the details <ArrowUpRight size={17}/></Link></section></div>;
}
