import { Link } from 'react-router-dom';
import { ArrowUpRight, CalendarDays, MessageCircle, Settings2 } from 'lucide-react';
import { ErrorState, Reveal } from '../Components/ui';
import { AccountHeader, AccountPanel, AccountSkeleton, ActivityList, CompactProjects, UserAvatar, asList, relativeTime, useAccountData } from '../Components/AccountComponents';
import { aggregatePortfolio } from '../utils/portfolio';
import { date, money } from '../utils/formatters';

export default function Profile() {
  const { data, error, loading, reload } = useAccountData({ user: '/users/me/', saved: '/community/saved/', following: '/community/following/', investments: '/investments/', comments: '/users/me/comments/', activity: '/community/activity/' });
  const user = data?.user;
  const saved = asList(data?.saved);
  const following = asList(data?.following);
  const comments = asList(data?.comments);
  const investments = asList(data?.investments);
  const totals = aggregatePortfolio(investments);
  return <div className="container account-page profile-page"><AccountHeader eyebrow="A SPACE THAT'S YOURS" title={<>Your perspective.<br /><span className="serif-emphasis">Your profile.</span></>} description="The ideas you keep, the questions you ask and the possibilities you're exploring." action={<Link to="/settings" className="btn btn-secondary"><Settings2 size={17} />Edit profile</Link>} />{loading ? <AccountSkeleton /> : error ? <ErrorState message={error} onRetry={reload} /> : user && <>
    <Reveal><section className="profile-identity-panel"><UserAvatar user={user} large /><div className="profile-identity-content"><span className="eyebrow">VESTRA EXPLORER</span><h2>{[user.first_name, user.last_name].filter(Boolean).join(' ') || user.username}</h2><p className="profile-email">{user.email}</p>{user.bio ? <p className="profile-bio">{user.bio}</p> : <p className="profile-bio muted">A little curiosity is a good place to begin. <Link to="/settings">Add your story.</Link></p>}<div className="profile-meta"><span><CalendarDays size={14} />Joined {date(user.date_joined)}</span><span>@{user.username}</span></div>{user.interests?.length > 0 && <div className="profile-interests" aria-label="Your interests">{user.interests.map((interest) => <Link key={interest} to={`/projects?category=${encodeURIComponent(interest)}`} className="badge">{interest}</Link>)}</div>}</div></section></Reveal>
    <div className="profile-stats-grid">{[{ label: 'Saved projects', value: user.counts?.saved ?? saved.length, to: '/saved' }, { label: 'Following', value: user.counts?.following ?? following.length, to: '/following' }, { label: 'Simulations', value: user.counts?.simulations ?? investments.length, to: '/portfolio' }, { label: 'Comments', value: user.counts?.comments ?? comments.length, to: '#your-comments' }].map((item) => <Link className="profile-stat-link" key={item.label} to={item.to}><strong>{item.value}</strong><span>{item.label}<ArrowUpRight size={15} /></span></Link>)}</div>
    <div className="profile-content-grid"><div className="profile-main-column"><div className="account-two-columns"><Reveal><AccountPanel title="Saved ideas" to="/saved"><CompactProjects projects={saved} emptyTitle="Your collection is waiting." /></AccountPanel></Reveal><Reveal delay={60}><AccountPanel title="Following" to="/following"><CompactProjects projects={following} emptyTitle="Stay close to an idea." /></AccountPanel></Reveal></div><Reveal><AccountPanel title="Your simulated portfolio" eyebrow="A BIGGER PICTURE" to="/portfolio" linkLabel="Open portfolio"><div className="profile-portfolio-preview"><div><span className="metric-label">Estimated simulated value</span><strong>{money(totals.value)}</strong><p>{money(totals.invested)} allocated across {totals.projectCount} {totals.projectCount === 1 ? 'project' : 'projects'}.</p></div><span className="portfolio-simulation-pill"><span />Simulation only</span></div>{investments.length === 0 && <Link to="/projects" className="text-link">Start your first simulation<ArrowUpRight size={15} /></Link>}</AccountPanel></Reveal><Reveal><section id="your-comments" className="account-panel profile-comments"><div className="account-panel-heading"><div><span className="eyebrow">YOUR VOICE, IN THE CONVERSATION</span><h2>Your comments</h2></div><MessageCircle size={20} /></div>{comments.length ? <ul className="profile-comment-list">{comments.slice(0, 12).map((comment) => <li key={comment.id}><div><Link to={`/projects/${comment.project_slug || comment.project}#comment-${comment.id}`}>{comment.project_title}<ArrowUpRight size={14} /></Link><time dateTime={comment.created_at}>{relativeTime(comment.created_at)}</time></div><p>{comment.body}</p><Link to={`/projects/${comment.project_slug || comment.project}#comment-${comment.id}`} className="text-link">View conversation<ArrowUpRight size={14} /></Link></li>)}</ul> : <div className="account-quiet-empty"><MessageCircle size={24} strokeWidth={1.3} /><strong>Every perspective adds something.</strong><p>Ask a question or share a thought on a project to join the conversation.</p><Link to="/projects" className="text-link">Find a discussion<ArrowUpRight size={15} /></Link></div>}</section></Reveal></div><Reveal><AccountPanel title="Recent activity" eyebrow="YOUR EXPLORATION, RECORDED" className="profile-activity-panel"><ActivityList activities={asList(data?.activity)} limit={8} /></AccountPanel></Reveal></div>
  </>}</div>;
}
