"""Metadata for the explicitly fictional catalogue, never real impact claims."""

DEMO_METADATA = {
    "Nova Energy": {"organization": "Nova Community Energy", "location": "Lagos, Nigeria", "impact_area": "Climate action", "impact_score": 88, "tags": ["Solar", "Community energy", "Carbon reduction"], "sustainability": ["Renewable generation", "Local maintenance teams", "Shared battery storage"]},
    "TerraGrid": {"organization": "TerraGrid Collective", "location": "Nairobi, Kenya", "impact_area": "Resource efficiency", "impact_score": 81, "tags": ["Smart cities", "Energy efficiency", "Technology"], "sustainability": ["Demand forecasting", "Less energy waste", "Existing infrastructure reuse"]},
    "AquaLoop": {"organization": "AquaLoop Cooperative", "location": "Accra, Ghana", "impact_area": "Water security", "impact_score": 92, "tags": ["Water reuse", "Circular economy", "Community"], "sustainability": ["Modular filtration", "Local operator training", "Reduced freshwater demand"]},
    "MedNova Labs": {"organization": "MedNova Access Labs", "location": "Kigali, Rwanda", "impact_area": "Health access", "impact_score": 84, "tags": ["Diagnostics", "Health access", "Local clinics"], "sustainability": ["Shared clinic equipment", "Shorter sample journeys", "Accessible screening"]},
    "Harvest AI": {"organization": "Harvest Field Cooperative", "location": "Nakuru, Kenya", "impact_area": "Food systems", "impact_score": 86, "tags": ["Agriculture", "Water efficiency", "Small farms"], "sustainability": ["Precision irrigation", "Farmer-led decisions", "Seasonal field feedback"]},
    "Solaris Communities": {"organization": "Solaris Neighbourhoods", "location": "Cape Town, South Africa", "impact_area": "Climate action", "impact_score": 90, "tags": ["Solar", "Community energy", "Shared spaces"], "sustainability": ["Underused land reuse", "Operator training", "Transparent generation reporting"]},
    "ClearWater Systems": {"organization": "ClearWater Service Network", "location": "Kumasi, Ghana", "impact_area": "Water security", "impact_score": 89, "tags": ["Clean water", "Rural infrastructure", "Maintenance"], "sustainability": ["Maintainable infrastructure", "Spare-part availability", "Water quality monitoring"]},
    "EduBridge": {"organization": "EduBridge Learning Network", "location": "Ibadan, Nigeria", "impact_area": "Learning access", "impact_score": 87, "tags": ["Education", "Digital inclusion", "Mentorship"], "sustainability": ["Shared learning devices", "Offline access", "Local facilitators"]},
    "GreenRoute": {"organization": "GreenRoute Urban Network", "location": "Nairobi, Kenya", "impact_area": "Sustainable cities", "impact_score": 82, "tags": ["Clean mobility", "Local business", "Urban logistics"], "sustainability": ["Electric cargo cycles", "Consolidated deliveries", "Neighbourhood hubs"]},
    "UrbanNest": {"organization": "UrbanNest Community Spaces", "location": "Lagos, Nigeria", "impact_area": "Sustainable cities", "impact_score": 79, "tags": ["Adaptive reuse", "Shared spaces", "Community"], "sustainability": ["Existing building reuse", "Energy retrofits", "Flexible interiors"]},
}
